### ISSUE TITLE
Use separate endpoint for joining a wifi network

### ISSUE THREAD

**Issue by larsblumberg** [getsenic/nuimo-hub-backend#30]
I.e. `/-/setup/wifi/join`

**Comment by tomster** [comment]
unless i misunderstand this request, we already have that feature. we simply `POST` the `ssid` and `password` to `/-/setup/wifi`.

how would or should this feature be different?

**Comment by larsblumberg** [comment]
It's more RESTy, /wifi/ returns available networks, POSTing to it should sementically not do a join. I suggest you have a quick chat with @grunskis, he's got a good point on it.

**Comment by grunskis** [comment]
I think we should stick to some REST guidelines. Probably our API won't be exposed to external world, but still it's nice to have also internal APIs nice.

**Comment by larsblumberg** [comment]
That's fixed – the endpoint to POST to is now `/setup/wifi/connection`
