### ISSUE TITLE
Cleanup playbooks

### ISSUE THREAD

**Issue by grunskis** [getsenic/nuimo-hub-backend#31]
For example playbook `hub-ubuntu` is doing some nice things that are generic and useful to run on a fresh raspbian installation. And it also contains `nuimo_hub` backend specific tasks which I might not want. They should go into their own playbook instead.

**Comment by tomster** [comment]
I agree, can you be more specific? :-)

**Comment by grunskis** [comment]
Created a more specific ticket here https://github.com/getsenic/nuimo-hub-backend/issues/84
