### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by wind-rider** [getsenic/nuimo-hub-backend#36]
Hi,

great to see that you're creating a hub! I saw that you're planning on supporting Raspberry Pi which is really nice.

Will it be possible to run this hub software as a docker container on Raspberry as well, so that you can easily install it and still use your Raspberry for other purposes? There is info about docker on Raspberry on https://blog.hypriot.com/.

**Comment by tomster** [comment]
no, we do not plan to support docker. we do, however, support running the hub via vagrant (https://github.com/getsenic/nuimo-hub-backend/tree/master/deployment#bootstrapping-vagrant)

**Comment by wind-rider** [comment]
@tomster / @larsblumberg Ok, that's a pity... Can you suggest where to start if I'd want to do that myself? I have not much experience with python, virtual environments and putting them in Docker so I'm still a bit confused where to start with this app and what to put in a docker image.

Also I see that there are deployment scripts meant for ploy; would I need to "reimplement" them in docker scripts?

**Comment by tomster** [comment]
@wind-rider ploy is just a wrapper and convenience script around the ansible playbooks that contain the actual 'meat' of the configuration. the best approach would be IMHO along the lines of integrating the playbook runs into your dockerfile.

i can't point you to anything specific, but i do know/remember that there are several approaches out there that incorporate ansible into docker based provisioning.

most approaches i recall installing python2.7 and ansible into the docker image itself, give it access to the roles via a mountpoint and then run ansible inside the docker image against localhost (i.e. itself).

i hope that helps, please let us know, if you have any further questions. we're not averse against supporting docker, we just don't have any expertise and/or immediate use for it :)
