### ISSUE TITLE
ENTER_SETUP_FLAG should be read from configuration file, not be hard coded

### ISSUE THREAD

**Issue by larsblumberg** [getsenic/nuimo-hub-backend#54]
We save all runtime files in `/srv/nuimo_hub/data`. It's good to have all files in one place and their paths configured via the configuration ini file.

Hence it's good if `commands.py` would read the path `ENTER_SETUP_FLAG` from the configuration file as we do with other paths, too.

Furthermore this setting is already in the config ini file as it's consumed already by tests.

**Comment by tomster** [comment]
great minds think alike :-) i've done this proactively on my development branch for #28 already in this commit 0e818f5b47d3ef2c9a3b87c06d197b309104f676

will be available once merged or feel free to cherrypick

**Comment by tomster** [comment]
has been merged
