### ISSUE TITLE
Pypi returning old package instead of the latest

### ISSUE THREAD

**Issue by larsblumberg** [getsenic/nuimo-hub-backend#89]
Currently packages created by Travis upload packages with version 0.0 instead of 0.1: https://travis-ci.org/getsenic/nuimo-hub-backend/builds/214684371

This leads to older packages with version 0.1 getting downloaded instead of latest packages build from master branch.

**Comment by tomster** [comment]
this has since been fixed by me removing test releases manually that had messed with the versioning scheme
